import MarketplaceToolbar from '@/components/marketplace/MarketplaceToolbar'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Orifuke Games",
  description: "Generated by create next app",
};

export default function MarketplaceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <section className="flex min-h-screen flex-col bg-slate-950 text-slate-100">
      <main className="flex-1">{children}</main>
    </section>
  );
}
